Implement a few independent naive "searching" classes
industrycrashcourse/dummyjvm pull request #22
Opened 2021-02-03 06:12 UTC by jakemannix

With a test harness class that simultaneously tests them all the same way.

2021-02-03 06:29 UTC, jakemannix commented
This branch now cleanly passes a couple of nontrivial tests, with two different "search" implementations.  

Assignment part 1: write a code review of this PR, and make a request for clarification on what the heck is going on.  No stupid questions, but no *repeat* questions.  Comment directly on changed files in the Github web UI, on the line that's confusing to you.  Point of the question is to get to understand the code and test well enough that you'd feel comfortable being one of the "two required reviewers" to allow this branch to merge to main.

2021-02-03 17:02 UTC, tylerastraub reviewed
What is the purpose of tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java if it is identical to tdd/src/main/java/edu/industrycrashcourse/dummy/search/SimpleTraversalInMemorySearchIndex.java, or vice versa? Is there a benefit to having two different versions of the same method even if under the hood, they are the same when it comes to performance and memory?

2021-02-03 17:04 UTC, tylerastraub commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +    public List<Long> search(String token, int numDocs) {
Sorry for repeat comment, I just now figured out how to comment directly on a line. Anyways:

What is the purpose of a repeat search() method in StreamsFilterTraversalSearchIndex.java if it is identical to the search() method in SimpleTraversalInMemorySearchIndex.java, or vice versa? Is there a benefit to having two different versions of the same method even if under the hood, they are the same when it comes to performance and memory?

2021-02-03 19:17 UTC, tridenmitchell commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +     * @param token   to find in the documents which have been indexed
Sorry for my lack of experience in java, what exactly are these @param statements doing and why are they commented out? I see that they are supposed to be used for finding indexed documents and the maximum number of results to return but I don't see it actually implemented.

2021-02-03 21:09 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +    public List<Long> search(String token, int numDocs) {
So both classes implement the same interface (TokenSearchIndex), so *have to* have the same methods and ideally perform the same functionality.

Typically you would not have different versions which have the same CPU / memory characteristics.  So my *next* implementation will be significantly faster, but I wanted to wait until we have a test which even bothers to measure latency / timing.  But it'll come at a cost: the "indexDocuments()" method will be much slower, as a tradeoff.

Other implementations of this interface which would make sense to have would be "DiskBackedIndex" which would be stable against crashes/restarts.  But yes, typically different implementations will have different properties, not just stylistic changes.

2021-02-03 21:11 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +     * @param token   to find in the documents which have been indexed
Ah ok.  This is "javadocs" - when you make these particular kind of "comment" for a method (or a class), there is code which turns it into HTML which looks like this: https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html

2021-02-03 21:34 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +     * @param token   to find in the documents which have been indexed
(they're not required, btw: they're just a way to automatically generate documentation - the compiler doesn't notice them, as they are comments)

2021-02-03 21:48 UTC, tridenmitchell commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +     * @param token   to find in the documents which have been indexed
Okay, that makes sense!

2021-02-03 21:48 UTC, tridenmitchell submitted a review, later dismissed

2021-02-04 04:15 UTC, tylerastraub submitted a review, later dismissed

2021-02-04 05:53 UTC, MattSamm requested changes

2021-02-04 05:53 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        assertArrayEquals(
I'm not quite sure what this assertArrayEquals function does. How does this sub-test check that the implementation returns the right indices? Is it just that the function assertArrayEquals makes sure the matches are in spots 1 and 2. What if our implementation doesn't match in these first two spots?

2021-02-04 09:47 UTC, dasar208 commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +                results.toArray(new Long[2])
I also have some confusion about `assertArrayEquals()`. According to [junit docs](https://junit.org/junit4/javadoc/4.12/org/junit/Assert.html#assertArrayEquals(boolean[],%20boolean[])), `assertArrayEquals()` accepts two parameters: one boolean array with expected values and another with actual values (btw I found a minor mistake in the docs - it should say actuals instead of expected for the description of the second parameter). However, in your code, you are passing three parameters: a string, and two arrays of longs. Why are you allowed to use different data types for the parameters than what is specified in the docs (boolean arrays)? Why are you allowed to use more parameters than what is specified in the docs (two)?

2021-02-04 10:14 UTC, dasar208 commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        assertEquals("No index should have zero length list", 0, results.size());
We saw from the previous assignment that if `index` and, consequently, `results` is null, then any subsequent assert statements do not run at all because the compiler returns an error (at line 35, in this case). So, why is the `assertNotNull()` statement necessary in line 36, considering that the program wouldn't reach that line if results were null. Why not have the `assertEquals()` on line 37 just by itself?

Also, what difference does it make that you added a message on the `assertEquals()` statement on line 37, as opposed to just leaving it without a message like in (the deleted) line 33? I am assuming it's because you have multiple `assert` statements so you would want to know which one is failing in case of a failure.

2021-02-04 22:19 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        assertArrayEquals(
assertArrayEquals does indeed check that the array is literally [1, 2] not [1, 2, 3] or [2, 1].  A valid question is: where in our product spec did we say what *order* the results come back.

Good catch, bonus points to you for this review! :)

2021-02-04 22:22 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        assertEquals("No index should have zero length list", 0, results.size());
if results is null, NPE will occur on line 37 if line 36 doesn't exist.

2021-02-04 22:57 UTC, jakemannix reviewed
bunch of suggestions!  take it or leave it.

2021-02-04 22:57 UTC, jakemannix commented on .github/workflows/maven.yml
> +        fail_ci_if_error: true
what the heck does this block do?

2021-02-04 22:57 UTC, jakemannix commented on tdd/pom.xml
> +    <scala.version>2.12.11</scala.version>
why 2.12.11 instead of 2.12.0 like before?

2021-02-04 23:52 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        "The matching documentIds should be 1 and 2", new Long[] {1L, 2L}, sortedResults);
hopefully this is better, @MattSamm ?

2021-02-05 00:07 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        "The matching documentIds should be 1 and 2", new Long[] {1L, 2L}, sortedResults);
so the test sorts the results now before checking (against the "artificial" long array ) that they match. looks good to me! the order should not matter now.

2021-02-05 00:07 UTC, MattSamm approved these changes

2021-02-05 03:32 UTC, lkeitadk approved these changes
Other than the confusing part about search returning more than allDocuments, everything looks good to me.

2021-02-05 03:32 UTC, lkeitadk commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +                .map(Map.Entry::getKey)
Pardon my lack of Java knowledge, but why are we returning allDocuments in additiion to all these functions? I am not sure of why they would be here.

2021-02-05 03:39 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +                .map(Map.Entry::getKey)
ah!  We are not returning allDocuments, nor are we returning any functions: we are returning the results of `(allDocuments.entrySet().stream().filter("that filter fn").limit(numDocs).map())`.

That is to say, we take `allDocuments`, we call the `entrySet()` method on that HashMap (here: https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#entrySet-- ), which returns a `Set<Map.Entry<Long, String>>`, then call the `stream()` method on that, and then the `filter()` method on that, and then the `limit()` method on that, and then the `map()` method on that, and finally the `collect()` method on that, which happens to return a `List<Long>` which is what the method signature of this method requires.

2021-02-05 03:44 UTC, dasar208 commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +                .map(Map.Entry::getKey)
When you talk about calling the different methods "on that," do you mean on the `allDocuments` HashMap or on whatever data the method called before it returned?

2021-02-05 03:48 UTC, merged

2021-02-05 03:50 UTC, dasar208 commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/StreamsFilterTraversalSearchIndex.java
> +                .map(Map.Entry::getKey)
Ah, nevermind, I didn't see the way you chained them all together. That makes it more clear.