OR Queries
industrycrashcourse/dummyjvm pull request #30
Opened 2021-02-09 05:18 UTC by lkeitadk

Just implemented support for OR querying, as well as the unit tests.

2021-02-09 22:04 UTC, tylerastraub requested changes
the code seems to work but there's a lot of tidying that could be done, as well as performance improvements - see comments

2021-02-09 22:04 UTC, tylerastraub commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/ORSensitiveSearchIndex.java
> +    for (String nonOrElem : nonOrElements) {
it is probably not an issue for our project, but on a larger scale, switching the order of these for loops may be more beneficial to performance. here, we are loading every single document twice, when we could instead load every document once and check through it twice.

2021-02-09 22:04 UTC, tylerastraub commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +    indexes.get(2).indexDocuments(docs);
i can't help but feel like calling .get(2) to refer to the ORSensitiveSearchIndex object hurts readability a lot, especially as the codebase becomes increasingly complex

2021-02-09 22:04 UTC, tylerastraub commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        "We should be matching docs 1, 2, 3 and 4", new Long[] {1L, 2L, 3L, 6L}, sortedResults);
i'm assuming you mean docs 1, 2, 3, and 6

2021-02-09 23:40 UTC, MattSamm submitted a review, later dismissed
I talked with Jake after class and it would be better if there were another class that enforced OR Queries instead of adding the test in the InMemoryTokenSearchIndex test class

2021-02-10 00:52 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/ORSensitiveSearchIndex.java
> +          if (resultDocIds.size() < numDocs && !resultDocIds.contains(documentEntry.getKey())) {
as you mentioned separately, this is probably due to the order of the looping: by looping over the separate boolean clauses ["foo", "bar"], we may find duplicates in the result set (i.e. a doc which matches both foo and bar.  So some de-duping is necessary, either here or at the end.

2021-02-10 00:56 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/ORSensitiveSearchIndex.java
> +    for (String nonOrElem : nonOrElements) {
Interestingly, while this is totally true when it come to our current implementation, which is a "full table scan" in DB-speak (and hence making *two* full-table scans would be double bad!), when I show y'all the way to do this with a better data structure, it turns out that the "outer loop" is indeed the query words, with the "inner loop" being documents, *specifically for* efficiency!

(but like I said, for the current case, design would suggest swapping them would be beneficial, you're correct, @tylerastraub )

2021-02-10 00:59 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        "We should be matching docs 1, 2, 3 and 4", new Long[] {1L, 2L, 3L, 6L}, sortedResults);
> I talked with Jake after class and it would be better if there were another class that enforced OR Queries instead of adding the test in the InMemoryTokenSearchIndex test class

yep.  @lkeitadk - let's create a new test class (OrSensitiveSearchIndexTest.java) which just tests your new class, and move your test methods into there.

2021-02-10 00:59 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +    indexes.get(2).indexDocuments(docs);
that should be fixed by moving this test method into it's own class

2021-02-10 01:26 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        "We should be matching docs 1, 2, 3 and 4", new Long[] {1L, 2L, 3L, 6L}, sortedResults);
In fact, @tylerastraub , this reminds me that the assertArrayEquals method will already compare the expected to actual arrays, so we don't need to list their contents in the fail message.  Simply stating the kind of expectation should be enough: "documents matching either 'foo' or 'bar' should be returned" (and JUnit will print out "expected: [1,2,3,6] \n actual: [1,2,3] (or whatever it actually is)")

2021-02-10 01:33 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/ORSensitiveSearchIndex.java
> +  protected Map<Long, String> allDocuments = new HashMap<>();
yep, default to private unless you think you'll share (I had a base class which had two subclass implementations, which is why I used protected)

2021-02-10 02:48 UTC, lkeitadk commented on tdd/src/test/java/edu/industrycrashcourse/dummy/TokenSearchIndexTest.java
> +        "We should be matching docs 1, 2, 3 and 4", new Long[] {1L, 2L, 3L, 6L}, sortedResults);
Working on it as of now

2021-02-10 03:25 UTC, lkeitadk commented
@tylerastraub @jakemannix @MattSamm Just updated the code and improved the cleanliness, please let me know if there is any major issue.

2021-02-10 03:32 UTC, tylerastraub submitted a review, later dismissed

2021-02-10 03:45 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/ORSensitiveSearchIndex.java
> +    // separated by " OR " (and OR with a space before and after itself).
helpful comment about limitations of initial implementation.  Often nice to also create a work item on the TODO list on our project page to track it, so if we were continuing to work on this project, we could decide later to fix / improve this issue.

2021-02-10 03:51 UTC, jakemannix requested changes
Almost perfect, just switch it so we check for duplicates with a Set while looping, instead of at the end, and we're good to go!

2021-02-10 03:51 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/ORSensitiveSearchIndex.java
> +          if (resultDocIds.size() < numDocs && !resultDocIds.contains(documentEntry.getKey())) {
Ok, so to @tylerastraub's point, let's fix this so that we only do this duplicate checking once, by changing `resultSetDocIds` to be a `Set<Long>` and then all the usage of it up until line 40 will still work (`.contains()`, `.size()`, and `.add()` all exist on `Set`).  Then replace the last 4 lines with just `return new ArrayList(resultSetDocIds);` and it should work.

2021-02-10 04:16 UTC, jakemannix approved these changes
Perfect, looks good to me!

2021-02-10 04:27 UTC, tridenmitchell approved these changes
Love the changes!

2021-02-10 04:31 UTC, merged