Added support for MultiWordMatching
industrycrashcourse/dummyjvm pull request #33
Opened 2021-02-10 03:29 UTC by tylerastraub

Queries like 'quick fox' match 'the quick brown fox jumps', and 'that fox sure is quick'. Additionally, queries surrounded by double quotes count as one word. For instance, 'quick "foo bar" fox' will match 'the quick brown foo bar fox jumps', but will not match 'the quick brown foo fox jumps over the bar'.

2021-02-10 04:39 UTC, lkeitadk approved these changes
I've been looking at this for a while and still haven't found anything wrong, so it's a yes for me x

2021-02-10 04:41 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/MultiWordMatchingSearchTest.java
> +                "The matching documentIds should be 3 and 4", new Long[] {3L, 4L}, sortedResults);
so, assertArrayEquals will already tell us mismatches between expected and actual results, so our fail message should just state what we were trying to do: "Expected 'big bad' to match  both in-order, as well as out-of order docs like '... big bar brown bad...'.

2021-02-10 04:43 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/MultiWordMatchingSearchTest.java
> +        List<Long> results = matchingSearch.search("foo \"too bar\" poo", 10);
we should probably also assert that something like "foo bar poo too" *does not* match with this query (since "too" and "bar" don't occur right after each other).

2021-02-10 04:50 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/MultiWordMatchingSearch.java
> +        if (token.length() - token.replace("\"", "").length() > 1) {
I think `token.indexOf("\"")` will yield -1 if there are no matches (https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#indexOf-int- ), so you can just check if indexOf > 0, much more efficient than this replace approach.

2021-02-10 04:51 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/MultiWordMatchingSearch.java
> +        System.out.println(tokens);
probably remove this debugging line :)

2021-02-10 04:58 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/MultiWordMatchingSearch.java
> +        return resultDocIds;
So here's where we're going to need to consolidate your approach with @lkeitadk 's.  

As you mentioned in your review of his PR, his loop order is the opposite of yours.  Can you see a way to add in his logic into your loops?  Perhaps have an outer boolean flag which checks for whether this query has OR or does not?  If not, your inner "if(tokenCount ==0)" is the correct adding logic.  But if there is an OR, token count can be anything.  So perhaps it's as simple as `if (queryHasOR || tokenCount == 0) { ` at that inner loop?

2021-02-10 05:04 UTC, jakemannix requested changes
Ok, I'm going to issue an update to make @lkeitadk 's class the only searching class on main, just named InMemoryTokenSearchIndex, which is the class that'll have all the functionality we need.  Your code will need to merge into it - perhaps mostly replacing the search() method with a version containing both the OR logic he had and your implicit AND logic.  I think as I mention in the comments, it should not be too bad.

2021-02-10 05:19 UTC, jakemannix commented
> # [Codecov](https://codecov.io/gh/industrycrashcourse/dummyjvm/pull/33?src=pr&el=h1) Report
> > ❗ No coverage uploaded for pull request base (`main@aff3b84`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> > The diff coverage is `n/a`.
> 
> [![Impacted file tree graph](https://camo.githubusercontent.com/1bde970bd31a14df18721ed0955879dea2b1176771cab048453ded7d3a079329/68747470733a2f2f636f6465636f762e696f2f67682f696e6475737472796372617368636f757273652f64756d6d796a766d2f70756c6c2f33332f6772617068732f747265652e7376673f77696474683d363530266865696768743d313530267372633d707226746f6b656e3d554a39414f4941425239)](https://codecov.io/gh/industrycrashcourse/dummyjvm/pull/33?src=pr&el=tree)
> 
> ```diff
> @@           Coverage Diff           @@
> ##             main      #33   +/-   ##
> =======================================
>   Coverage        ?   90.19%           
>   Complexity      ?       19           
> =======================================
>   Files           ?        5           
>   Lines           ?       51           
>   Branches        ?       10           
> =======================================
>   Hits            ?       46           
>   Misses          ?        4           
>   Partials        ?        1           
> ```
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/industrycrashcourse/dummyjvm/pull/33?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/industrycrashcourse/dummyjvm/pull/33?src=pr&el=footer). Last update [aff3b84...e8de5d8](https://codecov.io/gh/industrycrashcourse/dummyjvm/pull/33?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

very happy with the additional code coverage.  Follow the link to see how much higher your code coverage % just got - higher than 90%, I think?

2021-02-10 06:37 UTC, tylerastraub commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/MultiWordMatchingSearch.java
> +        if (token.length() - token.replace("\"", "").length() > 1) {
however, if there is just one quote then that wouldn't work. would need to continue looking for second quote (which can also be done with indexOf - that was my original solution). alternatively could just linearly search for first two quotes while marking the position along the way. however, i do not know the product specs, but i do wonder how long any given search query will be? is the performance difference going to be that great?

2021-02-10 16:24 UTC, tylerastraub commented on tdd/src/test/java/edu/industrycrashcourse/dummy/MultiWordMatchingSearchTest.java
> +        List<Long> results = matchingSearch.search("foo \"too bar\" poo", 10);
is that not asserted in the second document? "too bar" does not match "too who bar" and this is reflected in the test

2021-02-10 16:53 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/MultiWordMatchingSearchTest.java
> +        List<Long> results = matchingSearch.search("foo \"too bar\" poo", 10);
yes, but "too who bar" already doesn't match "foo" or "poo", so it would be excluded already on account of that.  Ideally you want a doc which has all the individual words, but not "too bar" directly sequentially.

2021-02-10 17:01 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/search/MultiWordMatchingSearch.java
> +        if (token.length() - token.replace("\"", "").length() > 1) {
ah I see what you're saying.  Yes, you want to check if there are two quotes, not just one.  Doing it this way is fine, performance-wise, as an operation on the query will be subleading in effect on performance compared to things that have to be done to each document.  (yeah, something like`int firstMatch = query.indexOf("\""); if (firstMatch >= 0 && query.indexOf("\"", firstMatch) >= 0)` will quickly catch for both of the first two matches without doing any String replacement, and isn't really that much more code, and is probably a little easier for the reader to follow what is going on)

2021-02-10 17:22 UTC, tylerastraub commented on tdd/src/test/java/edu/industrycrashcourse/dummy/MultiWordMatchingSearchTest.java
> +        List<Long> results = matchingSearch.search("foo \"too bar\" poo", 10);
ah oops you're right

2021-02-11 03:06 UTC, tridenmitchell approved these changes
Looks good to me!

2021-02-11 03:50 UTC, jakemannix commented
Why did you have to force push?  That's a bad sign, you shouldn't really have to do that...

<img width="893" alt="Screen Shot 2021-02-10 at 7 50 00 PM" src="https://user-images.githubusercontent.com/69129/107600648-366b2980-6bd9-11eb-8b92-5b67adc35f99.png">

2021-02-11 03:53 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/InMemoryTokenSearchIndex.java
> +          } else if (resultDocIds.size() >= numDocs) {
seem like there's some convoluted / duplicated result.size() checking here?

2021-02-11 03:55 UTC, jakemannix approved these changes
Excellent work, with extra credit option as well.

2021-02-11 04:17 UTC, tylerastraub commented
> 
> 
> Why did you have to force push? That's a bad sign, you shouldn't really have to do that...
> 
> <img alt="Screen Shot 2021-02-10 at 7 50 00 PM" width="893" src="https://user-images.githubusercontent.com/69129/107600648-366b2980-6bd9-11eb-8b92-5b67adc35f99.png">

this was the stack overflow i followed when i performed this:
https://stackoverflow.com/questions/39399804/updates-were-rejected-because-the-tip-of-your-current-branch-is-behind-its-remot

2021-02-11 05:30 UTC, lkeitadk approved these changes
Didn't see anything major

2021-02-11 05:30 UTC, lkeitadk commented on tdd/src/main/java/edu/industrycrashcourse/dummy/InMemoryTokenSearchIndex.java
> +          } else if (resultDocIds.size() >= numDocs) {
> seem like there's some convoluted / duplicated result.size() checking here?

This might be a dumb question but where does this seem to happen? He seems only do one check per loop, and this check seems to only happen in this specific loop

2021-02-11 05:57 UTC, merged

2021-02-11 06:11 UTC, dasar208 commented on tdd/src/main/java/edu/industrycrashcourse/dummy/InMemoryTokenSearchIndex.java
> +          } else if (resultDocIds.size() >= numDocs) {
I think he's saying that the `else if(...)` in line 81 should be just an `else` statement. I think it makes sense because line 79 is already checking for `result.size() < numDocs` so that means `else` will automatically check for `result.size() >= numDocs`, no need to specify it.

2021-02-11 08:23 UTC, jakemannix commented
> > Why did you have to force push? That's a bad sign, you shouldn't really have to do that...
> > <img alt="Screen Shot 2021-02-10 at 7 50 00 PM" width="893" src="https://user-images.githubusercontent.com/69129/107600648-366b2980-6bd9-11eb-8b92-5b67adc35f99.png">
> 
> this was the stack overflow i followed when i performed this:
> https://stackoverflow.com/questions/39399804/updates-were-rejected-because-the-tip-of-your-current-branch-is-behind-its-remot

They did that because they had done a git rebase.  Had you done a git rebase? (if so, why?!?)

2021-02-11 08:27 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/InMemoryTokenSearchIndex.java
> +          } else if (resultDocIds.size() >= numDocs) {
Yeah, what @dasar208  was saying - it seems the simpler to read logic would be to have two separate sequential ifs: 
```
if (results.size >= numDocs) { break; } 
if (tokenCount == 0 || hasQueryOr) { results.add(doc); }
```