Matt punctuation preprocessor update
industrycrashcourse/dummyjvm pull request #36
Opened 2021-02-11 03:23 UTC by MattSamm

2021-02-11 03:48 UTC, jakemannix commented
note: if you like this branch, you can just merge it onto your main one (that has other's reviews, and is attached to your work item)

2021-02-11 03:53 UTC, MattSamm commented
> note: if you like this branch, you can just merge it onto your main one (that has other's reviews, and is attached to your work item)

Do I have another branch? I don't belive I have another branch. I think this is the one linked to my work item? @jakemannix

2021-02-11 05:16 UTC, MattSamm commented on tdd/pom.xml
> +        -->
OK @jakemannix @tylerastraub

2021-02-11 05:17 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +                results_hyphen.size());
I think I've fixed it in the newest commit

2021-02-11 05:17 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +                results_hyphen.size());
@tylerastraub

2021-02-11 05:45 UTC, MattSamm commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +      case Character.OTHER_PUNCTUATION : return false; // !@#%&*;':",./?
i added an exception to treat a " as an exception.

2021-02-11 05:46 UTC, tylerastraub requested changes

2021-02-11 05:46 UTC, tylerastraub commented on tdd/pom.xml
> +        <!- On Maven verify phase, fail if any file
everything else look good but i am leaving this up for review until jake decides what to do about this plugin issue

2021-02-11 05:47 UTC, MattSamm commented on tdd/pom.xml
> +        <!- On Maven verify phase, fail if any file
ok sounds good

2021-02-11 06:18 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +      else if (Character.DASH_PUNCTUATION == Character.getType(c)){
so it seems like you're treating dashes totally different than any other punctuation.  I get that we listed in the examples for the work item that "joe-bob" should match "joe bob", but I think the idea would be that "some_python_class" would also match "some python class" as well, etc.

So I think what you want is a blanket "else" statement - just replace all punctuation characters with spaces?

2021-02-11 06:19 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +    String temp = "";
Incidentally - it's pretty inefficient in Java to make all these extra String objects.  You should probably use a StringBuffer - it's basically for exactly this kind of thing.

2021-02-11 06:20 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +public class punctuationTest {
Class names in Java should be CapitalCamelCase

2021-02-11 06:23 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +        index.indexDocuments(docs);
since you're using the same "data" in each of your tests, it might be nice (not necessary to do this, however), to move these lines from each of your two test methods into a `@Before public void setUp()` method: they would then get executed before each test.

2021-02-11 06:24 UTC, jakemannix commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +        List<Long> results_hyphen = index.search("joe bob", 10);
variables in java should be named camelCase, not snake_case (and *never* the dreaded snake_Camel, which at least you avoided ;) )

2021-02-11 06:27 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/InMemoryTokenSearchIndex.java
> +            PreprocessingFunctions::removePunctuationPreprocessor));
I wonder if we want to reverse the order of these preprocessors?  If you change your code to replace punctuation with the space character *first*, then we shrinkWhitespace (which will turn any consecutive whitespace into just one), then trimList (remove any trailing and leading whitespace on words), it seems we'd have things "as normalized as possible", right?

2021-02-11 06:29 UTC, jakemannix commented on tdd/pom.xml
> +        -->
I think we can let this go in so that @MattSamm can commit this - otherwise I think it's blowing up his ability to git commit.  We can revert the change once his branch goes in, and solve the root cause problem on his machine after.

2021-02-11 06:31 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +    if (Character.isJavaIdentifierStart(c)) {
this is a kinda weird choice.  Keeping $ is great, but we remove - but keep _?

But ok for now.

2021-02-11 06:33 UTC, jakemannix requested changes
Ok, minor changes and this is pretty much good to go.

2021-02-11 19:47 UTC, MattSamm commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +    if (Character.isJavaIdentifierStart(c)) {
so a hyphen in my code currently would get replaced by a space ' '. an underscore would be removed so a word matt_samm would become mattsamm. I think an underscore should act much like a hypen in our search.

2021-02-11 19:47 UTC, MattSamm commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +    if (Character.isJavaIdentifierStart(c)) {
ill add another case

2021-02-11 19:47 UTC, MattSamm commented on tdd/src/main/java/edu/industrycrashcourse/dummy/InMemoryTokenSearchIndex.java
> +            PreprocessingFunctions::removePunctuationPreprocessor));
That seems to make sense to me ill rearrange the order

2021-02-11 19:50 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +public class punctuationTest {
Ok but functions should have the first letter lowercase?

2021-02-11 20:00 UTC, MattSamm commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +      else if (Character.DASH_PUNCTUATION == Character.getType(c)){
I was thinking that a query with "matt#samm" shouldn't necessarily match  "matt samm" if we change it to "matt samm". I can definitely make it a blanket statement that all punctuation be changed to a space.

2021-02-11 20:09 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +        List<Long> results_hyphen = index.search("joe bob", 10);
should be fixed in my new commits

2021-02-11 20:09 UTC, MattSamm commented on tdd/src/test/java/edu/industrycrashcourse/dummy/punctuationTest.java
> +public class punctuationTest {
should be fixed now.

2021-02-11 21:09 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +      else if (Character.DASH_PUNCTUATION == Character.getType(c)){
yeah I think that's easiest, and covers the typical usage.  Think of a URL: google.com should match "google" as query, right?

2021-02-11 21:12 UTC, jakemannix commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +      else if (Character.DASH_PUNCTUATION == Character.getType(c)){
So I think you want *all* (non-") punctuation to be replaced with the whitespace character.  Then our other preprocessors will shrink them down to one space.

2021-02-11 22:05 UTC, tridenmitchell approved these changes

2021-02-11 22:05 UTC, tridenmitchell commented on tdd/pom.xml
> +        <!- On Maven verify phase, fail if any file
Would like to see this done a bit neater but it doesn't change the functionality of it.

2021-02-12 00:26 UTC, MattSamm commented on tdd/src/main/java/edu/industrycrashcourse/dummy/PreprocessingFunctions.java
> +    String temp = "";
I think I've fixed this

2021-02-12 00:27 UTC, MattSamm commented
@jakemannix @tylerastraub I think I have addressed everything. (besides moving my test data). Let me know if this warrants your approval

2021-02-12 02:58 UTC, tylerastraub approved these changes

2021-02-12 02:59 UTC, jakemannix approved these changes
nice, LGTM.

2021-02-12 03:01 UTC, merged